[workspace]
name = "epa"
version = "0.1.0"
description = "Combined environment for Football scraping and Shiny analysis"
authors = ["Pablo Arias <piariasneira@gmail.com>"]
channels = ["conda-forge", "r"]
platforms = ["linux-64"]

[tasks]

[dependencies]
r-base = ">=4.5,<4.6"
r-tidyverse = "*"
"r-data.table" = "*"
r-openxlsx = "*"
r-writexl = "*"
r-readxl = "*"
r-ggplot2 = "*"
r-cowplot = "*"
r-plotly = "*"
r-shiny = ">=1.13.0,<2"
r-rsconnect = "*"
r-arrow = ">=24.0.0,<25"
r-renv = ">=1.2.3,<2"
r-duckdb = ">=1.5.2,<2"
r-dbi = ">=1.3.0,<2"
shiny = ">=1.4.0,<2"
r-dt = ">=0.34.0,<0.35"
gifski = ">=1.34.0,<2"
ffmpeg = ">=8.1.1,<9"
